services:
  - type: web
    name: fanfic-portal
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /ping
    autoDeploy: true
